### ISSUE TITLE
Using 3D plugin with zstack

### ISSUE THREAD

**Issue by kldague** [SynPuCo/SynapseCounter#3]
Hi:

I am trying to analyze an .nd2 zstack that I first open with Bio-Formats importer plugin, however I am not getting Pre and Post synaptic counts with the 3D plugin; only colocalized and the number seems off. How can I get better results with the 3D version?

Thanks,

Kat

**Comment by Neurogorka** [comment]
Hi!
I believe it is an import problem. Once you have an RGB stack or stack with clearly assigned channels, everything should work.

**Comment by kldague** [comment]
Would I need to import it as a tif?

**Comment by Neurogorka** [comment]
Not necessarily. Fiji just needs to see it has channels and a stack (c1/n s1/n in the description). But if you have problems, then yes, better make a tiff stack export from the microscope program. If you use RGB, remember to use only pure red blue and green as channel colors

**Comment by kldague** [comment]
Anytime I import it or change to RGB format it has clearly assigned channels and a z series (z1/n). How would I change it from a z stack to a stack (s1/n)?

**Comment by Neurogorka** [comment]
It's same. I'm surprised it doesn't work. It will be easier if you send me file. I will take a look during the first week of March

**Comment by kldague** [comment]
Thank you! Attached is the file.

Thanks,

 R1548A_100x2xopticalzoom_CA1_zstack.nd2
<https://drive.google.com/file/d/1gbGHitoLREoLvuqu-_FrIcwXGk3vF44W/view?usp=drive_web>

Katerina Dague
BS in Biochemistry
North Park University Alumna
(815) 354-6399
katerinaldague@gmail.com

**Comment by kldague** [comment]
Hi:

Have you been able to take a look at my file with the 3D plugin?

Thank you!

**Comment by Neurogorka** [comment]
Hi Katerina!
Sorry, seems my previous reply wasn't delivered or saved for some reason. You file runs smoothly on my PC. I even installed the Synapse Counter version deposited here to exclude that use different releases... You have roughly 6000 pre and postsynaptic structures, and the complete synapses are around 3000. I did not apply proper size filters, this is what you clearly know better. But in general, you have a very nice staining and the plugin works nicely. And the numbers are close to what I usually have (a bit more, but I believe it's a matter of size filter). Your file is multi-channel, so select this option. Check that you select the right channels with your stainings. Otherwise, I have no further idea what could go wrong... Check binary options, the "black background" tick is off in my settings.

**Comment by kldague** [comment]
Thank you so much! It was the binary options! Be well!
